server:
  port: 8081
spring:
  application:
    name: hydp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.210.50:3306/hydp?useSSL=false&serverTimezone=UTC
    username: hydp
    password: XHPszFLy8P3yk73w

  redis:
    host: 101.34.210.50
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  jackson:
    default-property-inclusion: non_null  # JSON处理时忽略非空字段


mybatis-plus:
  type-aliases-package: com.hydp.entity #别名扫描包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    cn.hydp: debug